# Generated by Django 4.2.19 on 2025-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lab_manager', 'Lab Manager'), ('analyst', 'Analyst'), ('qa_officer', 'QA Officer'), ('customer_service', 'Customer Service'), ('client', 'Client')], max_length=20),
        ),
    ]
