# Generated by Django 4.2.19 on 2025-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_name_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('analyst', 'Analyst'), ('lab_manager', 'Lab Manager'), ('customer_service', 'Customer Service')], max_length=30),
        ),
    ]
