# Generated by Django 4.2.19 on 2025-05-11 12:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('catalog_number', models.CharField(blank=True, max_length=50)),
                ('lot_number', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('mL', 'Milliliter'), ('L', 'Liter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('mg', 'Milligram'), ('each', 'Each')], max_length=10)),
                ('date_received', models.DateField()),
                ('expiry_date', models.DateField()),
                ('storage_conditions', models.CharField(blank=True, max_length=100)),
                ('storage_location', models.CharField(max_length=100)),
                ('safety_data_sheet', models.FileField(blank=True, null=True, upload_to='sds/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reagent',
                'verbose_name_plural': 'Reagents',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('last_calibration_date', models.DateField()),
                ('next_calibration_due', models.DateField()),
                ('calibration_interval', models.PositiveIntegerField(default=365, help_text='Interval in days')),
                ('calibrated_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('working', 'Working'), ('maintenance', 'Under Maintenance'), ('broken', 'Out of Service')], default='working', max_length=20)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['next_calibration_due'],
            },
        ),
    ]
