# Generated by Django 5.2 on 2025-05-18 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_equipment_last_updated_equipment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='reagent',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
