# Generated by Django 5.2.1 on 2025-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_reagent_last_updated_reagent_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(choices=[('fibertec', 'Fibertec'), ('kjeltec_8200', 'Kjeltec 8200'), ('kjeltec_8400', 'Kjeltec 8400'), ('moisture_analyzer', 'Moisture Analyzer'), ('furnace', 'Furnace'), ('oven', 'Oven'), ('centrifuge', 'Centrifuge'), ('digestor', 'Digestor')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hours_worked', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('analyst', models.CharField(choices=[('analyst_a', 'Analyst A'), ('analyst_b', 'Analyst B'), ('analyst_c', 'Analyst C')], max_length=50)),
                ('status', models.CharField(choices=[('working', 'Working'), ('maintenance', 'Maintenance'), ('broken', 'Broken'), ('idle', 'Idle')], max_length=20)),
                ('signed_by', models.CharField(max_length=100)),
                ('reviewed_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
