# Generated by Django 3.2 on 2025-05-11 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='test_type',
            field=models.CharField(blank=True, choices=[('proximate', 'Proximate Analysis'), ('ge', 'Gross Energy'), ('vitamin', 'Vitamin Analysis'), ('aflatoxin', 'Aflatoxin Testing'), ('water', 'Water Analysis'), ('microbial', 'Microbial Analysis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample'),
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='assigned', max_length=20)),
                ('analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.testrequest')),
            ],
        ),
    ]
