# Generated by Django 3.2 on 2025-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20250511_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='result_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='results/'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
