# Generated by Django 4.2.19 on 2025-05-11 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0004_testassignment_review_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Test Assignment', 'verbose_name_plural': 'Test Assignments'},
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='result_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('submitted', 'Submitted for Review')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='test_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='samples.testrequest'),
        ),
    ]
