# Generated by Django 4.2.19 on 2025-05-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_testassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
    ]
