# Generated by Django 3.2 on 2025-05-11 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_remove_sample_client_remove_sample_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('feed', 'Feed'), ('water', 'Water'), ('ingredient', 'Raw Material'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='client_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='client_company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='client_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('feed', 'Feed'), ('water', 'Water'), ('ingredient', 'Raw Material'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
