# Generated by Django 4.2.19 on 2025-05-12 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0008_alter_testassignment_result_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='client_company',
        ),
        migrations.AddField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
