# Generated by Django 5.2.1 on 2025-05-16 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_remove_sample_client_company_sample_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='analyst',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='test_request',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='client_company_address',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='tests_required',
        ),
        migrations.AddField(
            model_name='sample',
            name='nature',
            field=models.CharField(default='Feed', max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='parameters',
            field=models.TextField(default='Proximate'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='analysis_types',
            field=models.CharField(default='Proximate', max_length=255),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='job_description',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='name_of_receiver',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='nature_of_samples',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='number_of_samples',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='organization',
            field=models.CharField(default='organization', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='parameters',
            field=models.TextField(default='Proximate'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='proposed_date_of_collection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='signature',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='total_amount_charged',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.client'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.client'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='TestAssignment',
        ),
    ]
