# Generated by Django 5.2.1 on 2025-05-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_client_remove_testassignment_analyst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.testrequest'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.client'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='total_amount_charged',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
