# Generated by Django 5.2.1 on 2025-05-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_sample_test_request_alter_testrequest_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='analysis_types',
            field=models.CharField(choices=[('proximate', 'Proximate'), ('aflatoxin', 'Aflatoxin'), ('gross_energy', 'Gross Energy'), ('metabolizable_energy', 'Metabolizable Energy'), ('vitamins', 'Vitamins')], default='proximate', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.client'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='job_description',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='name_of_receiver',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='parameters',
            field=models.TextField(blank=True, default='Proximate'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='signature',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='total_amount_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
