# Generated by Django 5.2.1 on 2025-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_remove_analystprofile_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testassignment',
            name='sample',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='samples',
            field=models.ManyToManyField(to='samples.sample'),
        ),
    ]
