# Generated by Django 5.2.1 on 2025-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_remove_testassignment_sample_testassignment_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
