# Generated by Django 5.2.1 on 2025-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_testassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
