# Generated by Django 5.2.1 on 2025-05-22 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_testrequest_review_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequest',
            name='review_comments',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='review_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_test_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_test_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
