# Generated by Django 5.2.1 on 2025-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0020_reviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='test_type',
            field=models.CharField(choices=[('PROX', 'Proximate'), ('AFLX', 'Aflatoxin'), ('GREN', 'Gross Energy'), ('VIT', 'Vitamins'), ('WAT', 'Water'), ('MIC', 'Microbial')], default='PROX', max_length=4),
        ),
    ]
