# Generated by Django 5.2.1 on 2025-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0022_testrequest_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
