# Generated by Django 5.2.1 on 2025-05-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0024_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
