# Generated by Django 5.2.1 on 2025-05-22 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0025_rename_amount_invoice_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('test_parameter', models.CharField(max_length=100)),
                ('result_value', models.CharField(max_length=100)),
                ('method_reference', models.CharField(default='AOAC', max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
            ],
        ),
    ]
